name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ 505c505197c4777ae5c92a6046898dbe }}
          TIMEZONE: Asia/Seoul
